### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by matthiasbeyer** [Leetcore/audiothek-downloader#3]
I tried this:

```
python3 ./audiothek.py --url "https://www.ardaudiothek.de/sendung/legion-hacking-anonymous/12015417/"
```

and it immediately exited without doing anything.

**Comment by Leetcore** [comment]
Did you run the setup step? Requests should be installed. I tried your command line and it started downloading. I'm using Python 3.11.

**Comment by matthiasbeyer** [comment]
Yes, requests is available.

**Comment by Leetcore** [comment]
Please use venv to install all needed libs.
